name: Build and Store

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  actions: read
  contents: write

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # This enables task distribution via Nx Cloud
      # Run this command as early as possible, before dependencies are installed
      # Learn more at https://nx.dev/ci/reference/nx-cloud-cli#npx-nxcloud-startcirun
      - name: Enable task distribution via Nx Cloud
        run: npx nx-cloud start-ci-run --distribute-on="4 linux-medium-js" --stop-agents-after="release"

      - name: Read Node.js version from .nvmrc file
        run: |
          NODE_VERSION=$(cat .nvmrc)
          echo "NODE_VERSION=$NODE_VERSION" >> $GITHUB_ENV
          echo "NODE_VERSION=$NODE_VERSION"

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Verify the integrity of provenance attestations and registry signatures for installed dependencies
        run: npm audit signatures

      - name: Derive appropriate SHAs for base and head for `nx affected` commands
        uses: nrwl/nx-set-shas@v4

      - name: Check formatting
        run: npx nx format:check

      # Prepend any command with "nx-cloud record --" to record its logs to Nx Cloud
      # - run: npx nx-cloud record -- echo Hello World
      # Nx Affected runs only tasks affected by the changes in this PR/commit. Learn more: https://nx.dev/ci/features/affected
      - name: Lint affected
        run: npx nx affected -t lint

      - name: Test affected
        run: npx nx affected -t test

      - name: Set version affected
        run: npx nx release version

      - name: Build affected
        run: npx nx affected -t build

      - name: E2E affected
        run: npx nx affected -t e2e-ci

      - name: Generate CHANGELOG affected
        run: npx nx affected -t release -- --type=changelog

      - name: Publish affected
        run: npx nx affected -t release -- --type=publish
