name: Delete PR Releases on Close

on:
  pull_request:
    types:
      - closed

jobs:
  delete_prerelease_and_tag:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ssh-key: ${{secrets.PUSH_KEY}}

      - name: Delete associated release and tag
        run: |
          gh auth login

          pr_number=${{ github.event.pull_request.number }}
          repo=${{ github.repository }}

          # Fetch all releases associated with this PR
          releases=$(gh release list --limit 100 | grep -E "PR-${pr_number}")
          echo "Releases found: $releases"

          # Exit early if no releases are found
          if [ -z "$releases" ]; then
            echo "No releases found for PR-${pr_number}. Exiting."
            exit 0
          fi

          # Loop through releases and delete them along with tags
          while IFS= read -r release; do
            release_name=$(echo $release | awk '{print $1}')
            echo "Deleting release: $release_name"
            gh release delete $release_name --yes

            # Extract the tag from the release name and delete the tag
            tag=$release_name
            echo "Deleting tag: $tag"
            git push origin :refs/tags/$tag
          done <<< "$releases"
